services:
  - type: web
    name: tradingview-telegram-bot
    env: python
    buildCommand: pip install -e .
    startCommand: gunicorn --bind 0.0.0.0:$PORT --reuse-port main:app
    envVars:
      - key: ALPHA_VANTAGE_API_KEY
        sync: false
      - key: SESSION_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: tradingview_telegram_db
          property: connectionString

  - type: worker
    name: tradingview-telegram-worker
    env: python
    buildCommand: pip install -e .
    startCommand: python worker.py
    envVars:
      - key: ALPHA_VANTAGE_API_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: tradingview_telegram_db
          property: connectionString

databases:
  - name: tradingview_telegram_db
    databaseName: tradingview_telegram
    user: tradingview_telegram_user